---
name: Bug Report
about: File a bug report
title: "[Bug]: "
labels: bug
assignees:
  -HeyImAmethyst
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior:
      placeholder: 1.Go to '...' 2.Click on '....' 3.Scroll down to '....' 4.See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you playing on?
      options:
        - 1.18.2
        - 1.19.2
        - 1.19.3
        - 1.19.4
        - 1.20
        - 1.20.1
      default: 0
    validations:
      required: true
  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod Loader
      description: Are you using Forge or Fabric?
      options:
        - Forge
        - Fabric
  - type: textarea
    id: crash-log
    attributes:
      label: Crash Log
      description: If you can provide the crash log, put the contents of it here. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: true
---
