---
name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: enhancement
assignees:
  -HeyImAmethyst

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: describe-the-feature
    attributes:
      label: Describe the Feature
      description: A clear and concise description of what you want to the feature to be.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
---
